use db20168047
drop TABLE STUD_MEMBER;
drop TABLE DEPARTMENT;
CREATE TABLE STUD_MEMBER(Roll_No int,FName varchar(50),MName varchar(50),SName varchar(50),
      Dept_ID int,Semester int,Contact_No int,Gender varchar(1))ENGINE=InnoDB;

CREATE TABLE DEPARTMENT(Dept_ID int,Dept_Name varchar(50), primary key (Dept_ID))ENGINE=InnoDB;

INSERT INTO STUD_MEMBER(Roll_No,FName,MName,SName,Dept_ID,Semester,Contact_No,Gender)
Values(1,'ANKUR','SAMIR','KAHAR',1,1,272121,'M'),
      (2,'DHAVAL','DHIREN','J0SHI',1,1,232122,'M'),
      (3,'ANKITA','BIREN','SHAH',1,1,112121,'F'),
      (10,'KOMAL','MAHESHKUMAR','PANDYA',2,3,123123,'F'),
      (13,'AMIT','JITENKUMAR','MEHTA',3,3,453667,'M'),
      (23,'JINAL','ASHISH','GANDHI',2,1,323232,'M'),
      (22,'GANESH','ASHA','PATEL',2,3,124244,'M'),
      (4,'SHWETA','MIHIR','PATEL',3,1,646342,'F'),
      (7,'POOJA','MAYANK','DESAI',3,3,328656,'F'),
      (8,'KOMAL','KRISHNARAJ','BHATIA',2,3,257422,'F'),
      (43,'KIRAN','VIRAJ','SHAH',1,1,754124,'F');
      
INSERT INTO DEPARTMENT (Dept_ID,Dept_Name)
Values (1,'Information Technology'),
       (2,'Electrical'),
       (3,'Civil'),
       (4,'Mechanical'),
       (5,'Chemical');

ALTER TABLE STUD_MEMBER ADD FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID);


SELECT FName,Contact_No FROM STUD_MEMBER;
SELECT Roll_No,FName FROM STUD_MEMBER INNER JOIN DEPARTMENT ON DEPARTMENT.Dept_ID=STUD_MEMBER.Dept_ID WHERE Dept_Name='Information Technology';
SELECT Dept_Name FROM DEPARTMENT INNER JOIN STUD_MEMBER ON DEPARTMENT.Dept_ID=STUD_MEMBER.Dept_ID GROUP BY DEPARTMENT.Dept_ID;
SELECT Dept_Name FROM DEPARTMENT LEFT JOIN STUD_MEMBER ON DEPARTMENT.Dept_ID=STUD_MEMBER.Dept_ID WHERE STUD_MEMBER.Dept_ID IS NULL;
SELECT Dept_Name FROM DEPARTMENT;
SELECT COUNT(*) FROM STUD_MEMBER INNER JOIN DEPARTMENT ON DEPARTMENT.Dept_ID=STUD_MEMBER.Dept_ID WHERE DEPARTMENT.Dept_Name='Electrical';
SELECT * FROM STUD_MEMBER WHERE FName LIKE 'A%';
SELECT * FROM STUD_MEMBER WHERE Gender='M';
SELECT * FROM STUD_MEMBER WHERE Semester=3;
SELECT * FROM STUD_MEMBER WHERE Gender='F' ORDER BY FName; 
